#!/usr/bin/env node
// Builds the Awesome-CV LaTeX sources (and, with --pdf, the PDFs) from src/data/cv.yaml.
// Output: cv/build/cv-<lang>.tex and public/cv/loic-gouarin-cv-<lang>.pdf.

import { execFileSync } from 'node:child_process';
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const root = new URL('../', import.meta.url);
const buildDir = new URL('cv/build/', root);
const publicDir = new URL('public/cv/', root);
const LANGS = ['fr', 'en'];

// Colours measured on the owner's original PDF: section and location accent, header links.
const ACCENT = '327C8C';
const SOCIAL = '6CE0F1';

const cv = parse(await readFile(new URL('src/data/cv.yaml', root), 'utf8'));
const { publications } = JSON.parse(await readFile(new URL('src/data/publications.json', root), 'utf8'));

const tr = (value, lang) => (value == null ? '' : typeof value === 'string' ? value : value[lang] ?? '');

// Keep a section title with the start of its content instead of stranding it at a page bottom.
const heading = (title) => `\\needspace{6\\baselineskip}\n\\cvsection{${title}}\n`;

const TEX_SPECIALS = { '\\': '\\textbackslash{}', '&': '\\&', '%': '\\%', $: '\\$', '#': '\\#', _: '\\_', '{': '\\{', '}': '\\}', '~': '\\textasciitilde{}', '^': '\\textasciicircum{}' };
const tex = (s) => String(s).replace(/[\\&%$#_{}~^]/g, (c) => TEX_SPECIALS[c]);
const t = (value, lang) => tex(tr(value, lang));

const items = (list, lang) =>
  list?.length ? `\\begin{cvitems}\n${list.map((i) => `  \\item {${t(i, lang)}}`).join('\n')}\n\\end{cvitems}` : '';

const href = (url) => url.replace(/[%#]/g, (c) => `\\${c}`);

// Repository URLs print without their scheme so they fit the location column.
function place(value, lang) {
  const text = tr(value, lang);
  return /^https?:\/\//.test(text) ? `\\href{${href(text)}}{${tex(text.replace(/^https?:\/\//, ''))}}` : tex(text);
}

function entries(section, lang) {
  const rows = section.entries.map((e) => {
    const description = e.paragraph ? t(e.paragraph, lang) : items(e.items, lang);
    return `\\cventry{${t(e.position, lang)}}{${t(e.org, lang)}}{${place(e.location, lang)}}{${t(e.dates, lang)}}{${description}}`;
  });
  return `${heading(t(section.title, lang))}\n\\begin{cventries}\n${rows.join('\n\n')}\n\\end{cventries}`;
}

const honors = (list, lang) =>
  `\\begin{cvhonors}\n${list
    .map((h) => `\\cvhonor{${t(h.position, lang)}}{${t(h.title, lang)}}{${t(h.location, lang)}}{${t(h.dates, lang)}}`)
    .join('\n')}\n\\end{cvhonors}`;

function skills(section, lang) {
  const rows = section.entries.map((s) => `\\cvskill{${t(s.type, lang)}}{${t(s.set, lang)}}`);
  return `${heading(t(section.title, lang))}\n\\begin{cvskills}\n${rows.join('\n')}\n\\end{cvskills}`;
}

const TYPES = {
  fr: { preprint: 'Prépublication', report: 'Rapport', 'book-chapter': 'Chapitre', 'conference-paper': 'Communication' },
  en: { preprint: 'Preprint', report: 'Report', 'book-chapter': 'Chapter', 'conference-paper': 'Conference paper' },
};

function papers(lang) {
  const rows = publications.map((p) => {
    const authors = p.authors.map((a) => (a.self ? `\\textbf{${tex(a.name)}}` : tex(a.name))).join(', ');
    const kind = TYPES[lang][p.type];
    const venue = [kind, p.venue].filter(Boolean).map(tex).join(', ');
    const link = p.doi ?? p.open;
    const title = link ? `\\href{${href(link)}}{${tex(p.title)}}` : tex(p.title);
    return `\\cventry{${authors}}{${title}}{${p.year}}{}{${venue}}`;
  });
  // The titles are in English, so they use English punctuation even in the French CV.
  const list = `\\begin{cventries}\n${rows.join('\n\\vspace{1.6mm}\n')}\n\\end{cventries}`;
  return `${heading(t(cv.publications.title, lang))}\n${lang === 'fr' ? `\\begin{otherlanguage}{english}\n${list}\n\\end{otherlanguage}` : list}`;
}

// Formatted here rather than with \\today, which would follow the English publication block in the French CV.
const footerDate = (lang) =>
  new Intl.DateTimeFormat(lang === 'fr' ? 'fr-FR' : 'en-GB', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date());

function document(lang) {
  const h = cv.header;
  const teaching = cv.teaching.groups
    .map((g) => `\\cvsubsection{${t(g.title, lang)}}\n\n${honors(g.entries, lang)}`)
    .join('\n');
  return `% Generated by scripts/build-cv.mjs from src/data/cv.yaml. Do not edit.
\\documentclass[11pt, a4paper]{awesome-cv}
\\geometry{left=1.4cm, top=.8cm, right=1.4cm, bottom=1.8cm, footskip=.5cm}
\\definecolor{cvaccent}{HTML}{${ACCENT}}
\\colorlet{awesome}{cvaccent}
\\definecolor{cvsocial}{HTML}{${SOCIAL}}
\\renewcommand*{\\headersocialstyle}[1]{{\\fontsize{6.8pt}{1em}\\headerfont\\color{cvsocial} #1}}
\\renewcommand{\\acvHeaderSocialSep}{\\BeginAccSupp{ActualText={}}\\quad{\\color{lighttext}\\textbar}\\quad\\EndAccSupp{}}
\\usepackage{needspace}
% Wider date and location columns than the class default, so dates like "2017 - 2019, 2024" and places stay on one line.
\\renewenvironment{cvhonors}{%
  \\vspace{\\acvSectionContentTopSkip}\\vspace{-2mm}
  \\begin{center}\\setlength\\tabcolsep{0pt}\\setlength{\\extrarowheight}{0pt}
  \\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}} L{2.8cm} L{\\textwidth - 6.3cm} R{3.5cm}}
}{\\end{tabular*}\\end{center}}
% Same entry as the class, with a 5.6cm location column so repository links fit on one line.
\\renewcommand*{\\cventry}[5]{%
  \\vspace{-2.0mm}\\setlength\\tabcolsep{0pt}\\setlength{\\extrarowheight}{0pt}
  \\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}} L{\\textwidth - 5.6cm} R{5.6cm}}
    \\ifempty{#2#3}
      {\\entrypositionstyle{#1} & \\entrydatestyle{#4} \\\\}
      {\\entrytitlestyle{#2} & \\entrylocationstyle{#3} \\\\
      \\entrypositionstyle{#1} & \\entrydatestyle{#4} \\\\}
    \\ifstrempty{#5}{}{\\multicolumn{2}{L{\\textwidth}}{\\descriptionstyle{#5}} \\\\}
  \\end{tabular*}%
}
\\setbool{acvSectionColorHighlight}{true}
\\usepackage[english, ${lang === 'fr' ? 'main=french' : 'main=english'}]{babel}

\\photo[circle,noedge,left]{loic_small.png}
\\name{${tex(h.firstName)}}{${tex(h.lastName)}}
\\position{${t(h.position, lang)}}
\\email{${tex(h.email)}}
\\github{${tex(h.github)}}
\\linkedin{${tex(h.linkedin)}}
\\x{${tex(h.x)}}

\\begin{document}
\\makecvheader[R]
\\makecvfooter{${tex(footerDate(lang))}}{${tex(h.firstName)} ${tex(h.lastName)}~~~·~~~Curriculum Vitae}{\\thepage}

${entries(cv.experience, lang)}

${skills(cv.skills, lang)}

${entries(cv.education, lang)}

${entries(cv.projects, lang)}

${heading(t(cv.activities.title, lang))}
${honors(cv.activities.entries, lang)}

${heading(t(cv.teaching.title, lang))}
${teaching}

${papers(lang)}

${heading(t(cv.hobbies.title, lang))}
\\begin{cvparagraph}
${t(cv.hobbies.text, lang)}
\\end{cvparagraph}

\\end{document}
`;
}

await mkdir(buildDir, { recursive: true });
await copyFile(new URL('cv/awesome-cv.cls', root), new URL('awesome-cv.cls', buildDir));
await copyFile(new URL('src/assets/loic_small.png', root), new URL('loic_small.png', buildDir));
for (const lang of LANGS) await writeFile(new URL(`cv-${lang}.tex`, buildDir), document(lang));
console.log(`LaTeX sources written to cv/build/ (${LANGS.join(', ')}).`);

if (process.argv.includes('--pdf')) {
  await mkdir(publicDir, { recursive: true });
  for (const lang of LANGS) {
    // Two passes so page references and the footer settle.
    for (let pass = 0; pass < 2; pass++) {
      try {
        execFileSync('xelatex', ['-interaction=nonstopmode', '-halt-on-error', `cv-${lang}.tex`], {
          cwd: buildDir,
          // The vendored Source Sans 3 and Roboto fonts live in cv/fonts, registered by cv/fonts.conf.
          env: { ...process.env, FONTCONFIG_FILE: fileURLToPath(new URL('cv/fonts.conf', root)) },
          stdio: 'ignore',
        });
      } catch {
        // XeLaTeX reports errors in its log, not on stderr: show the first one.
        const log = await readFile(new URL(`cv-${lang}.log`, buildDir), 'utf8');
        const at = log.indexOf('\n!');
        console.error(at >= 0 ? log.slice(at, at + 1200) : log.slice(-1200));
        throw new Error(`xelatex failed on cv-${lang}.tex`);
      }
    }
    await copyFile(new URL(`cv-${lang}.pdf`, buildDir), new URL(`loic-gouarin-cv-${lang}.pdf`, publicDir));
    console.log(`public/cv/loic-gouarin-cv-${lang}.pdf`);
  }
}
