// Generated by scripts/fetch-publications.mjs; do not edit publications.json by hand.
import data from './publications.json';

export type Publication = {
  id: string;
  title: string;
  year: number;
  type: string;
  venue: string | null;
  authors: { name: string; self: boolean }[];
  doi: string | null;
  open: string | null;
};

export const publications: Publication[] = data.publications;
export const publicationsFetchedAt: string = data.fetchedAt;
